import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Nav from "./Nav";

const Home: NextPage = () => {
  const enterprise_list =
    api.amapi.enterprises_list.useQuery().data?.data.enterprises;

  const displayEnterprisesList = () => {
    return enterprise_list?.map((item) => {
      return (
        <Link
          className="hover:opacity-50"
          key={item.name}
          href={{
            pathname: "/Dashboard",
            query: {
              enterpriseName: item.name,
            },
          }}
        >
          <p className="text-light-cyan">{item.enterpriseDisplayName}</p>
          <hr className="border-neon-green border drop-shadow-xl" />
        </Link>
      );
    });
  };

  return (
    <>
      <Head>
        <title>Andromeda</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/andromeda.png" />
      </Head>
      <main className="bg-dark-grayish-blue h-screen w-screen">
        <div className="container mx-auto py-8">
          <Nav />
          <div className="border-neon-green mx-auto mt-16 min-h-[70vh] w-1/3 rounded-lg border-4 px-8 py-4">
            <h3 className="text-light-cyan text-center">Choose an enteprise</h3>
            <p className="text-light-cyan mb-4 text-center">
              to continue to{" "}
              <span className="text-neon-green">Andromeda Console</span>
            </p>
            {displayEnterprisesList()}
          </div>
          {/* <button>Create enterprise</button> */}
        </div>
      </main>
    </>
  );
};

export default Home;
